GET http://localhost:3000/


###
// GET ALL ASSETS
GET http://localhost:3000/assets


###
// CREATE ASSET
POST http://localhost:3000/assets

Content-Type: application/json
{
    "id": "asset2",
    "symbol": "A1",
    "price": 50
}


###
// DELETE SPECIFIC ASSET
DELETE http://localhost:3000/assets

Content-Type: application/json
{
    "id": "asset2"
}